# Generated by Django 3.1.5 on 2021-02-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unknown_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='stop_time',
            new_name='end_time',
        ),
    ]
