# Generated by Django 3.1.6 on 2021-02-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unknown_calendar', '0002_auto_20210203_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
